Get block device info
labring/sealfs pull request #99
Opened 2023-02-14 12:35 UTC by HHoflittlefish777

Get block info.

2023-02-14 13:35 UTC, luanshaotong requested changes
Your PR needs more complete implement.

2023-02-15 06:53 UTC, uran0sH commented
I think you should propose an RFC first.

2023-02-15 13:47 UTC, HHoflittlefish777 commented
> I think you should propose an RFC first.

So, it is become the first RFC?

2023-02-15 13:59 UTC, luanshaotong commented
I think the main issue with this PR is completeness. At the same time, it is difficult for others to continue to work on the basis of this PR, if the author gives up. So please submit a standalone module that does not require subsequent implementation.
The RFC does not affect this issue. Of course, it would be great to have an RFC.

2023-03-02 02:58 UTC, uran0sH commented
Why not use crossbeam-skiplist directly? Do you think your skiplist performance is better than it?

2023-03-02 03:00 UTC, uran0sH requested changes

2023-03-02 03:00 UTC, uran0sH commented on src/server/storage_engine/block_device/block_storage.rs
>  pub trait BlockStorage {
Why need this trait?

2023-03-02 03:16 UTC, HHoflittlefish777 commented
> Why not use crossbeam-skiplist directly? Do you think your skiplist performance is better than it?

There are two reasons. First, the library has not been updated for five years. Some places are incompatible with the new one. Or if there is a problem, who can solve it? Second, in our scenario, we need to merge data blocks of the same kind, so from this perspective, I think it may not be suitable

2023-03-02 03:24 UTC, uran0sH commented
So what's difference between your skiplist and comman skiplist?
> Second, in our scenario, we need to merge data blocks of the same kind, so from this perspective,

2023-03-02 03:35 UTC, uran0sH commented
https://github.com/crossbeam-rs/crossbeam/tree/master/crossbeam-skiplist Are you sure this hasn't been updated in five years?
> First, the library has not been updated for five years

2023-03-02 03:46 UTC, HHoflittlefish777 commented
> https://github.com/crossbeam-rs/crossbeam/tree/master/crossbeam-skiplist Are you sure this hasn't been updated in five years?
> 
> > First, the library has not been updated for five years

It is my mistake.

2023-03-02 14:11 UTC, luanshaotong commented
I think you need to implement call route from storage_engine to your block interface, even it is a demo or mock.

2023-03-03 03:05 UTC, closed without merging